version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile  # Ahora usará el Dockerfile correcto
    ports:
      - "3000:80"  # Mapeo correcto para nginx (puerto 80)
    depends_on:
      backend:
        condition: service_started
    networks:
      app-network:
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://backend:5000/api  # Configuración correcta para React

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID:-default-project}
      - LLM_SERVICE_URL=http://llm_service:8000
    depends_on:
      - mongodb
      - llm_service
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./backend/src:/app/src
      - ./backend/src/credentials:/app/src/credentials

  llm_service:
    build:
      context: ./llm_service
      dockerfile: Dockerfile  
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
      - HUGGINGFACEHUB_API_TOKEN=${HUGGINGFACEHUB_API_TOKEN}
    networks:
      - app-network
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: