version: "3.9"  
services:  
  frontend:  
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:  
      - "3000:80"  
    depends_on:  
      - backend  
    networks:
      - app-network

  backend:  
    build: ./backend  
    ports:  
      - "5000:5000"  
    environment:  
      - NODE_ENV=production
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
    volumes:
      - ./backend/src:/app/src
      - ./backend/firebase-credentials.json:/app/src/firebase-credentials.json:ro
    networks:
      - app-network

networks:
  app-network:
    driver: bridge