version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile 
    ports:
      - "3000:80"  
    depends_on:
      backend:
        condition: service_started  
    networks:
      - academic-network
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID}
      - FIREBASE_CLIENT_CERT_URL=${FIREBASE_CLIENT_CERT_URL}
      - LLM_SERVICE_URL=http://rag_service:8000
    depends_on:
      rag_service:
        condition: service_started  
    networks:
      - academic-network
    restart: unless-stopped
    volumes:
      - ./backend/src:/app/src

  rag_service:
    build:
      context: ./llm_service
      dockerfile: Dockerfile  
    ports:
      - "8000:8000"
    environment:
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_CREDENTIALS_PATH=/app/firebase-credentials.json
      - GROQ_API_KEY=${GROQ_API_KEY}
      - TZ=America/Bogota
    volumes:
      - ./backend/src/credentials/firebase-credentials.json:/app/firebase-credentials.json:ro
      - ./logs/rag:/app/logs
    networks:
      - academic-network
    restart: unless-stopped

networks:
  academic-network:
    driver: bridge
    name: sistema-academico-red