version: "3.9"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile 
    ports:
      - "3000:80"  
    depends_on:
      backend:
        condition: service_started
    networks:
      app-network:
    restart: unless-stopped
    environment:
      - REACT_APP_API_URL=http://backend:5000/api  

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_PRIVATE_KEY_ID=${FIREBASE_PRIVATE_KEY_ID}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_CLIENT_ID=${FIREBASE_CLIENT_ID}
      - FIREBASE_CLIENT_CERT_URL=${FIREBASE_CLIENT_CERT_URL}
      - LLM_SERVICE_URL=http://llm_service:8000
    depends_on:
      - llm_service
    networks:
      - app-network
    restart: unless-stopped
    volumes:
      - ./backend/src:/app/src

  llm_service:
    build:
      context: ./llm_service
      dockerfile: Dockerfile  
    ports:
      - "8000:8000"
    environment:
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID:-proyecto-final-gestordatos}
      - FIREBASE_CREDENTIALS_PATH=/app/firebase-credentials.json
      - HUGGINGFACEHUB_API_TOKEN=${HUGGINGFACEHUB_API_TOKEN}
    volumes:
      - ./backend/src/credentials/firebase-credentials.json:/app/firebase-credentials.json:ro
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge